"""empty message

Revision ID: 716e9875cff6
Revises: a74b7f87527b
Create Date: 2025-01-29 16:36:10.421544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716e9875cff6'
down_revision = 'a74b7f87527b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sobrenome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
